# fájl: azure-pipelines.yml
trigger:
  - main

parameters:
  - name: env
    type: string
    default: 'Dev'

variables:
  - name: compileTimeVar
    value: ${{ parameters.env }}
  - name: compileExprVar
    value: ${{ format('CT-{0}', parameters.env) }}
  - name: compileIfVar
    ${{ if eq(parameters.env, 'Dev') }}:
      value: DevelopmentMode
    ${{ else }}:
      value: ProductionMode
  - name: staticVar
    value: 'staticValue'
  - name: runtimeConcatVar
    value: $[ format('RT-{0}', variables.staticVar) ]
  - name: macroVar
    value: $(staticVar)
  - name: agentOSVar
    value: $(Agent.OS)
  - name: envSuffix
    ${{ if eq(parameters.env, 'Dev') }}:
      value: '-dev'
    ${{ else }}:
      value: '-prod'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: PrintVars
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "compileTimeVar:   $(compileTimeVar)"
              echo "compileExprVar:   $(compileExprVar)"
              echo "compileIfVar:     $(compileIfVar)"
              echo "staticVar:        $(staticVar)"
              echo "runtimeConcatVar: $(runtimeConcatVar)"
              echo "macroVar:         $(macroVar)"
              echo "agentOSVar:       $(agentOSVar)"
              echo "envSuffix:        $(envSuffix)"
            displayName: 'Print all variables'

  # --- Új, csak Dev környezetben futó stage ---
  - stage: DevOnly
    displayName: 'Dev Only Stage'
    condition: eq(variables['compileTimeVar'], 'Dev')
    jobs:
      - job: EchoDev
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo "This is the Dev-only stage"
            displayName: 'Dev echo'

  # --- Új, csak nem-Dev környezetben (pl. Prod) futó stage ---
  - stage: ProdOnly
    displayName: 'Production Only Stage'
    condition: ne(variables['compileTimeVar'], 'Dev')
    jobs:
      - job: EchoProd
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo "This is the Production-only stage"
            displayName: 'Prod echo'
