# fájl: azure-pipelines.yml
trigger:
  - main

parameters:
  - name: env
    type: string
    default: 'Dev'

variables:
  # 1) paraméterből vett érték (compile-time)
  compileTimeVar: ${{ parameters.env }}

  # 2) compile-time kifejezés format-tal
  compileExprVar: ${{ format('CT-{0}', parameters.env) }}

  # 3) compile-time if-else (template expression)
  compileIfVar: ${{ parameters.env == 'Dev' ? 'DevelopmentMode' : 'ProductionMode' }}

  # 4) statikus literal változó
  staticVar: 'staticValue'

  # 5) runtime kifejezés format-tal
  runtimeConcatVar: $[ format('RT-{0}', variables['staticVar']) ]

  # 6) runtime if-else (runtime expression)
  runtimeIfVar: $[ eq( variables['staticVar'], 'staticValue' ) ? 'Yes' : 'No' ]

  # 7) makró-szintű változó
  macroVar: $(staticVar)

  # 8) rendszer-változó
  agentOSVar: $(Agent.OS)

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: PrintVars
        displayName: 'Print all variable types + conditions'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "compileTimeVar:       $(compileTimeVar)"
              echo "compileExprVar:       $(compileExprVar)"
              echo "compileIfVar:         $(compileIfVar)"
              echo "runtimeConcatVar:     $(runtimeConcatVar)"
              echo "runtimeIfVar:         $(runtimeIfVar)"
              echo "macroVar:             $(macroVar)"
              echo "agentOSVar:           $(agentOSVar)"
            displayName: 'Print variables'
