# fájl: azure-pipelines.yml
trigger:
  - main

parameters:
  - name: env
    type: string
    default: 'Dev'

variables:
  # 1) paraméterből vett érték (compile-time)
  - name: compileTimeVar
    value: ${{ parameters.env }}

  # 2) compile-time format
  - name: compileExprVar
    value: ${{ format('CT-{0}', parameters.env) }}

  # 3) compile-time if/else – az első példa
  - name: compileIfVar
    ${{ if eq(parameters.env, 'Dev') }}:
      value: DevelopmentMode
    ${{ else }}:
      value: ProductionMode

  # 4) statikus literal változó
  - name: staticVar
    value: 'staticValue'

  # 5) runtime format
  - name: runtimeConcatVar
    value: $[ format('RT-{0}', variables.staticVar) ]

  # 6) makró-szintű változó
  - name: macroVar
    value: $(staticVar)

  # 7) rendszer-változó
  - name: agentOSVar
    value: $(Agent.OS)

  # 8) compile-time if/else – második példa, környezeti suffix
  - name: envSuffix
    ${{ if eq(parameters.env, 'Dev') }}:
      value: '-dev'
    ${{ else }}:
      value: '-prod'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: PrintVars
        displayName: 'Print variables + conditions'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "compileTimeVar:   $(compileTimeVar)"
              echo "compileExprVar:   $(compileExprVar)"
              echo "compileIfVar:     $(compileIfVar)"
              echo "staticVar:        $(staticVar)"
              echo "runtimeConcatVar: $(runtimeConcatVar)"
              echo "macroVar:         $(macroVar)"
              echo "agentOSVar:       $(agentOSVar)"
              echo "envSuffix:        $(envSuffix)"
            displayName: 'Print all variables'
